name: CI / CD
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: knowsuchagency/poetry-install@v2
      
      - name: Run Tests
        run: poetry run py.test

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: knowsuchagency/poetry-install@v2

      - name: Run the build process
        run: poetry run pyinstaller --onefile preprocessor.py

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: preprocessor-${{ matrix.os }}
          path: |
            dist

  prerelease:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
      
      - name: Prerelease commits
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true

  release:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
      
      - name: Release tags
        uses: softprops/action-gh-release@v1
